### ISSUE TITLE
Script link is broken

### ISSUE THREAD

**Issue by sinak** [giuem/ga-proxy#2]
The `Script` link in the readme is broken.

Is this project functioning?

**Comment by giuem** [comment]
Which IP did you get? And what status code, 4xx or 5xx?

BTW, if visit the link directly, it will return 400 error. To test the server, you can visit https://ga.giuem.com/detect, and it should return 200.

Try to run the command below to make a test
```
curl -I -X GET https://ga.giuem.com/detect
```

**Comment by giuem** [comment]
I have fixed the broken script link (c787eba4c83f5bba1d8647a4c8e758032916df48)
