### ISSUE TITLE
Redirecting to the repo

### ISSUE THREAD

**Issue by jb33k** [giuem/ga-proxy#5]
I'm testing the code, followed the instructions, but I'm having a curious behavior where everything redirects to this repo. For example, when I try /detect, it does 302 redirect to this repo.

Am I missing something here?

*edit*
I checked the code and if I'm understanding it right, pageviews are sent to /p and timings to /t. The thing is that both of these are redirecting to the repo now. Curiously enough /ping works correctly.

**Comment by giuem** [comment]
The server checks HTTP Referer and `ga` in query. 
https://github.com/giuem/ga-proxy/blob/master/server/router.go#L11

**Comment by jb33k** [comment]
> The server checks HTTP Referer and `ga` in query.
> https://github.com/giuem/ga-proxy/blob/master/server/router.go#L11

Interesting. I just grabbed the url that redirects from the dev tools and it looks like this `/t?plt=882&dns=0&pdt=3&rrt=0&tcp=0&srt=95&dit=513&clt=513&dt=example&de=UTF-8&ul=en-US&sd=24-bit&sr=2560x1440&vp=1647x1373&z=1561468053307`. Does this look correct?

**Comment by jb33k** [comment]
Found the problem. This was a page cache issue and now I can see ga parameters correctly set in the url. Thanks for your help!
